### ISSUE TITLE
Has Cypress been contacted about this?

### ISSUE THREAD

**Issue by lworkman** [NicholasBoll/cypress-enter-plugin#1]
Hey, 

Just found your library, and I'm wondering if you've been in touch with Cypress at all about typing enter triggering a click. It truly seems like something Cypress should support, and I'd be surprised if no one else has opened an issue with them.

**Comment by NicholasBoll** [comment]
Thanks. I filed an issue when I created this plugin: https://github.com/cypress-io/cypress/issues/8267

Today I dug even deeper because a coworker was trying to detect if the spacebar key would check a checkbox element. Some time ago I recommended people not test the default behavior of elements. But the reason this coworker wanted to test the spacebar key made be rethink and look deeper.

In their application, there was a global `keydown` listener that called `event.preventDefault()` on "non actionable" elements. The problem was this "non actionable" function was broken and was calling `event.preventDefault()` for the spacebar key on `input[type=checkbox]` and they wanted to ensure this functionality worked with Cypress. It turns out this wasn't possible. Well, it is possible due to a bug in Cypress if the element is not focused: https://github.com/cypress-io/cypress/issues/8267#issuecomment-743918524

After figuring out what the issue was, I offered an assertion function to detect default prevented keyboard events. But this got me thinking about a more inclusive plugin than this one. You could try out https://github.com/NicholasBoll/cypress-keyboard-plugin instead

**Comment by lworkman** [comment]
Oh interesting! Thanks for the link.
